<a href="https://colab.research.google.com/github/Ommanchanda/Machine_Learning/blob/main/Ensemble_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings('ignore')

In [2]:
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split

In [3]:
x,y=make_classification(n_samples=1000,n_features=20,n_classes=2,random_state=1)

In [4]:
x

array([[-2.04582165, -0.13791624, -0.08071423, ...,  2.48194524,
         0.74236675,  0.23154789],
       [-0.98726024,  1.30120189,  2.37734888, ...,  0.55445754,
        -0.21892143, -0.37608578],
       [ 0.57335921,  0.09375582,  0.4662521 , ..., -0.6088508 ,
         0.79903499, -0.17121177],
       ...,
       [-0.70737159,  1.07650943,  0.58510456, ..., -1.51337602,
         0.90239871, -0.69230951],
       [-0.20706849,  1.17319848, -1.94478665, ..., -0.32820676,
         1.5711921 ,  1.14877729],
       [-2.16769231, -2.54871672,  2.89359255, ...,  0.71535366,
         0.34329241,  1.07350284]])

In [5]:
y

array([0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [6]:
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=1,test_size=0.3)

In [7]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB

In [8]:
lr=LogisticRegression()
dt=DecisionTreeClassifier()
sv=SVC()
gn=GaussianNB()

In [9]:
from sklearn.ensemble import VotingClassifier

In [11]:
ensemble_clf=VotingClassifier(estimators=[('logistic_reg',lr),('decision_tree_clf',dt),('support_vector_clf',sv),('gaussian',gn)],voting='hard')

In [13]:
ensemble_clf.fit(x_train,y_train)

VotingClassifier(estimators=[('logistic_reg', LogisticRegression()),
                             ('decision_tree_clf', DecisionTreeClassifier()),
                             ('support_vector_clf', SVC()),
                             ('gaussian', GaussianNB())])

In [14]:
y_pred=ensemble_clf.predict(x_test)

In [15]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.8533333333333334

**ENSEMBLE REGRESSOR**

In [16]:
from sklearn.datasets import make_regression

In [17]:
x,y=make_regression(n_samples=1000,n_features=10,noise=0.1,random_state=1)

In [18]:
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=1,test_size=0.3)

In [19]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR

In [21]:
lin_reg=LinearRegression()
dtr=DecisionTreeRegressor()
svr=SVR(kernel='linear')

In [22]:
from sklearn.ensemble import VotingRegressor

In [27]:
ens_reg=VotingRegressor(estimators=[('lr',lin_reg),('dtr',dtr),('svr',svr)])

In [28]:
ens_reg.fit(x_train,y_train)

VotingRegressor(estimators=[('lr', LinearRegression()),
                            ('dtr', DecisionTreeRegressor()),
                            ('svr', SVR(kernel='linear'))])

In [29]:
y_pred=ens_reg.predict(x_test)
y_pred

array([  77.11858092,   93.50544653, -160.03530158,  -41.09780415,
        503.06534907,  229.84205005,   83.26938089,  -88.39521595,
        -70.09210316,   46.2997566 , -100.76549805,   17.28468425,
        -88.29059199, -151.52503124, -326.8217538 , -167.3320576 ,
       -288.64248817, -145.96823296,  -40.38979116, -114.76839428,
        -68.64520719, -139.13073358,  302.52607018, -168.70106267,
          4.4332108 ,  223.97146452,  329.09456446,   95.11880656,
        -92.80829259,   88.73338947,   45.36350172,  260.37576037,
        133.98494945,  228.74772991,  159.68039331,  173.85063077,
        103.89229201, -430.31075212, -175.83121274, -156.5560992 ,
         -6.88942426,  -93.7308362 ,   82.00288017, -244.20511211,
         61.20852287,  156.56796197,  278.4159567 , -155.14816186,
        137.99556247, -300.48634537,  257.95506766,  350.56047495,
       -171.50969975,   77.8788902 , -143.79064907,   67.77747886,
        169.73426713,   41.57595705,   79.74338091,   64.53474

In [31]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.9545037879421263