<a href="https://colab.research.google.com/github/Ommanchanda/Machine_Learning/blob/main/Ridge_Lasso_Imp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Ridge,Lasso Implementation**

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings('ignore')

In [3]:
df=sns.load_dataset('mpg')

In [4]:
df

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0    18.0          8         307.0       130.0    3504          12.0   
1    15.0          8         350.0       165.0    3693          11.5   
2    18.0          8         318.0       150.0    3436          11.0   
3    16.0          8         304.0       150.0    3433          12.0   
4    17.0          8         302.0       140.0    3449          10.5   
..    ...        ...           ...         ...     ...           ...   
393  27.0          4         140.0        86.0    2790          15.6   
394  44.0          4          97.0        52.0    2130          24.6   
395  32.0          4         135.0        84.0    2295          11.6   
396  28.0          4         120.0        79.0    2625          18.6   
397  31.0          4         119.0        82.0    2720          19.4   

     model_year  origin                       name  
0            70     usa  chevrolet chevelle malibu  
1            70     usa          buick skylark 320  
2            70     usa         plymouth satellite  
3            70     usa              amc rebel sst  
4            70     usa                ford torino  
..          ...     ...                        ...  
393          82     usa            ford mustang gl  
394          82  europe                  vw pickup  
395          82     usa              dodge rampage  
396          82     usa                ford ranger  
397          82     usa                 chevy s-10  

[398 rows x 9 columns]

In [5]:
df1=df.drop('name',axis=1)

In [6]:
df1

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0    18.0          8         307.0       130.0    3504          12.0   
1    15.0          8         350.0       165.0    3693          11.5   
2    18.0          8         318.0       150.0    3436          11.0   
3    16.0          8         304.0       150.0    3433          12.0   
4    17.0          8         302.0       140.0    3449          10.5   
..    ...        ...           ...         ...     ...           ...   
393  27.0          4         140.0        86.0    2790          15.6   
394  44.0          4          97.0        52.0    2130          24.6   
395  32.0          4         135.0        84.0    2295          11.6   
396  28.0          4         120.0        79.0    2625          18.6   
397  31.0          4         119.0        82.0    2720          19.4   

     model_year  origin  
0            70     usa  
1            70     usa  
2            70     usa  
3            70     usa  
4            70     usa  
..          ...     ...  
393          82     usa  
394          82  europe  
395          82     usa  
396          82     usa  
397          82     usa  

[398 rows x 8 columns]

In [7]:
df1['origin'].value_counts()

origin
usa       249
japan      79
europe     70
Name: count, dtype: int64

In [8]:
df1.isnull().sum()

mpg             0
cylinders       0
displacement    0
horsepower      6
weight          0
acceleration    0
model_year      0
origin          0
dtype: int64

In [9]:
df1['horsepower'].median()

93.5

In [10]:
df1['horsepower']=df1['horsepower'].fillna(df1['horsepower'].median())

In [11]:
df1.isnull().sum()

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model_year      0
origin          0
dtype: int64

In [12]:
df1['origin']=df1['origin'].map({'usa':1  ,  'japan':2  , 'europe': 3})

In [13]:
df1['origin']

0      1
1      1
2      1
3      1
4      1
      ..
393    1
394    3
395    1
396    1
397    1
Name: origin, Length: 398, dtype: int64

In [14]:
x=df1.drop('mpg',axis=1)
y=df1[['mpg']]

In [15]:
y.shape

(398, 1)

In [16]:
x.shape

(398, 7)

In [17]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)

In [18]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()

In [19]:
model.fit(x_train,y_train)

LinearRegression()

In [20]:
model.coef_

array([[-0.2165378 ,  0.01987994, -0.01270482, -0.0071647 ,  0.09047637,
         0.84604207,  1.42800007]])

In [21]:
model.intercept_

array([-24.46818219])

In [22]:
x_train.shape

(318, 7)

In [23]:
from sklearn.metrics import r2_score

y_pred_linear=model.predict(x_test)
r2_linear =r2_score(y_test,y_pred_linear)
r2_linear

0.856301245145641

In [24]:
from sklearn.linear_model import Ridge

In [25]:
rr=Ridge(alpha=0.1)

In [26]:
rr.fit(x_train,y_train)

Ridge(alpha=0.1)

In [27]:
rr.coef_

array([-0.21615305,  0.01986222, -0.01269732, -0.00716443,  0.0904574 ,
        0.84597471,  1.4266691 ])

In [28]:
y_pred=rr.predict(x_test)

In [29]:
r2_ridge=r2_score(y_pred,y_test)
r2_ridge

0.8524848915756948

In [30]:
from sklearn.linear_model import Lasso

In [31]:
lr=Lasso(alpha=0.5)

In [32]:
lr.fit(x_train,y_train)

Lasso(alpha=0.5)

In [33]:
lr.coef_

array([-0.        ,  0.00197727, -0.00929169, -0.00658993,  0.        ,
        0.75320801,  0.        ])

In [34]:
y_pred_l=lr.predict(x_test)

In [35]:
r2_lasso=r2_score(y_pred_l,y_test)
r2_lasso

0.8409773536392986

In [36]:
from sklearn.linear_model import ElasticNet

In [37]:
enm=ElasticNet(alpha=1,l1_ratio=0.5)
enm.fit(x_train,y_train)

ElasticNet(alpha=1)

In [38]:
enm.coef_

array([-0.        ,  0.0015385 , -0.01064196, -0.00653261,  0.        ,
        0.72035415,  0.        ])

In [39]:
enm_y=enm.predict(x_test)

In [40]:
r2_enm=r2_score(enm_y,y_test)
r2_enm

0.841610727344146

In [1]:
# Hyperparameter tuning

In [41]:
from sklearn.model_selection import GridSearchCV,RandomizedSearchCV

In [42]:
from sklearn.linear_model import Ridge,Lasso

In [43]:
lasso=Lasso()

In [44]:
param_grid={'alpha':[0.001,0.01,0.1,1,10,100]}

In [46]:
grid_search=GridSearchCV(estimator=lasso,param_grid=param_grid,cv=5,scoring='r2',verbose=2)

In [47]:
grid_search.fit(x_train,y_train)

Fitting 5 folds for each of 6 candidates, totalling 30 fits
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ........................................

GridSearchCV(cv=5, estimator=Lasso(),
             param_grid={'alpha': [0.001, 0.01, 0.1, 1, 10, 100]}, scoring='r2',
             verbose=2)

In [49]:
grid_search.best_params_

{'alpha': 0.1}

In [50]:
grid_search.best_score_

np.float64(0.7977657505718685)

In [53]:
y_pred_new=grid_search.best_estimator_.predict(x_test)

In [54]:
r2_score(y_pred_new,y_test)

0.8512576126849094

In [57]:
param_grid={'alpha':[0.001,0.01,0.1,1,10,100]}

In [61]:
random_search=RandomizedSearchCV(estimator=lasso,param_distributions=param_grid,cv=5,scoring='r2',verbose=2)

In [62]:
random_search

RandomizedSearchCV(cv=5, estimator=Lasso(),
                   param_distributions={'alpha': [0.001, 0.01, 0.1, 1, 10,
                                                  100]},
                   scoring='r2', verbose=2)

In [63]:
random_search.fit(x_train,y_train)

Fitting 5 folds for each of 6 candidates, totalling 30 fits
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ........................................

RandomizedSearchCV(cv=5, estimator=Lasso(),
                   param_distributions={'alpha': [0.001, 0.01, 0.1, 1, 10,
                                                  100]},
                   scoring='r2', verbose=2)

In [67]:
random_search.best_estimator_

Lasso(alpha=0.1)

In [68]:
y_pred_new2=random_search.best_estimator_.predict(x_test)

In [69]:

r2_score(y_pred_new2,y_test)

0.8512576126849094

In [70]:
#RIDGE gridsearch CV

In [71]:
ridge=Ridge()
ridge=GridSearchCV(estimator=ridge,param_grid=param_grid,cv=5,scoring='r2',verbose=2)

In [73]:
ridge.fit(x_train,y_train)

Fitting 5 folds for each of 6 candidates, totalling 30 fits
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ........................................

GridSearchCV(cv=5, estimator=Ridge(),
             param_grid={'alpha': [0.001, 0.01, 0.1, 1, 10, 100]}, scoring='r2',
             verbose=2)

In [74]:
ridge.best_params_

{'alpha': 10}

In [75]:
ridge.best_estimator_

Ridge(alpha=10)

In [76]:
y_pred_new3=ridge.best_estimator_.predict(x_test)

In [77]:
r2_score(y_test,y_pred_new3)

0.8563494248817896